#TOKEN: '1527372965:AAEhXiPnEyXuivLLNo7Wio5T6FOIJ0eejU8'
TOKEN: '5128003219:AAEAZKq1HxdcYpd-OYl8FyC36GJLyYEHBeo'

authorized_ids: {
  0: 876999143
}

citats : {
  0: 'Посмотрите на брови! Они настолько суровы, что им можно пиво открывать! Они мерзкие. Хуже даже чем вся остальная физиономия. Они бросаются в глаза, будто хотят отделиться от лица и основать собственное государство бровей!',
  1: '— Бойся меня, я убил сотни повелителей времени. — Бойся МЕНЯ, я убил их всех.',
  2: '— Думаю, ты ее герой. — Я не герой. — Так и я тоже, но если мы оба продолжим притворяться ими... Возможно, благодаря этому другие станут героями. Возможно, мы оба превратимся в легенды. И пусть они никогда не кончаются.',
  3: 'Будучи молодым телепатом, я знал одну уловку. Конечно, с дверями нельзя установить психическую связь, а все потому, что они чертовски обижены. Ну представьте жизнь двери: люди проходят мимо, всё стучат, но ради кого-то другого... Но если ты хоть немного приветлив...',
  4: 'Вселенная невозможна. Она полна чудес и загадок.',
  5: 'Как люди могут скучать? Как вообще была изобретена скука?',
  6: 'Вода терпелива, Аделаида. Вода умеет ждать. Точит камень горы, весь мир. Вода всегда выигрывает.',
  7: 'Определенные моменты фиксируются. Крошечные драгоценные минуты. Все движется, произойти может, что угодно, но отдельные фрагменты неизменны.',
  8: 'Фашизм — это когда говорят, как надо жить, кого любить, кто должен жить, а кто умереть. Ты сражался за то, чтобы мы все могли делать, что мы хотим, и говорить, что хотим, а ты стал, как они.',
  9: 'Да что с вами такое люди? Слышите голоса — пытаетесь их заткнуть, деревья пришли на помощь — пытаетесь их уничтожить.',
  10: 'Некоторые решения слишком важны, чтобы перекладывать их на чужие плечи.',
  11: 'Ничего не бывает так, как ожидаешь. Всегда есть место удивлению.',
  12: 'Кто-то за двадцать лет делает больше, чем другой — за восемьдесят. Главное — не время, главное — человек.',
  13: 'Никто из нас не знает, что нас ждет. Поэтому мы продолжаем искать. Продолжайте верить. Путешествуйте с надеждой. Вселенная вас удивит... всегда.',
  14: '— Это бред? Я обезумел? — Бред? Ну, офицера времён Первой Мировой на Южном полюсе по застывшему времени преследует пришелец. Бред не бывает таким интересным.',
  15: 'Мы не жертвуем людьми — это неправильно, потому что — это легко.',
  16: 'Где есть слезы, есть и надежда.',
  17: '— Что является противоположностью резни? — И что же? — По моему опыту — объяснение!',
  18: 'Знаешь, почему я всегда выигрываю в шахматы? У меня есть секретный ход — опрокинуть доску.',
  19: 'Новый рот — новые правила.',
  20: '— Куда мы идём? — Понятия не имею, но если я буду выглядеть целенаправленным, то они подумают, что у меня есть план.',
  21: 'Истинный облик Вселенной ты видишь только когда она просит тебя о помощи.',
  22: 'Страх бесполезен. Мы должны быть любимы.',
  23: '— Это другое небо. Оно из чего-то другого сделано? Из чего это небо? — Из леденцов. — Правда? — Нет, но было бы здорово, правда?',
  24: 'Жизнь — просто воспоминание.',
  25: '— И это значит, что мы снова можем стать друзьями. — Ты правда так думаешь? — Не знаю. Но надежда — такая опасная штука. И такая 30: ''соблазнительная.',
  26: '— Миллиарды будут страдать и умирать! — Я буду страдать, если убью тебя. — Больше, чем любое живое существо во Вселенной? — Да.',
  27: '— Ты отправляешься в путешествие, которое закончится твоей гибелью. — То же самое можно сказать и о новорожденном.',
  28: 'Или я просто в аду? Это ничего, ада я не боюсь. Это просто рай для плохих людей.',
  29: 'Любить Доктора — все равно что любить звезды. Разве кто-то ждет, что закат солнца ответит взаимностью?',
  30: 'О, я выжил. Чудесно. Люблю так делать.',
  31: '— Они создали психопатку, чтобы она тебя убила. \n— А я на ней женился.'
}